INFO:root:Automation Framework Logs

INFO:root: Starting test case Login_out
INFO:root: Android Mobile picked[UDID: 3300f4b7d5f56461, VERSION: 8.1.0]
INFO:root: initialization done in Action_funcs
INFO:selenium.webdriver.remote.remote_connection:Could not connect to port 4723 on host localhost
INFO:selenium.webdriver.remote.remote_connection:Could not get IP address for host: localhost
DEBUG:selenium.webdriver.remote.remote_connection:POST http://localhost:4723/wd/hub/session {"desiredCapabilities": {"platformVersion": "8.1.0", "platformName": "Android", "udid": "3300f4b7d5f56461", "fullReset": "false", "automationName": "UiAutomator2", "noReset": "true", "newCommandTimeout": "3600", "deviceName": "Device", "appActivity": "com.mavenir.ucc.tab.TabActivity", "appPackage": "com.mavenir.gmid"}, "capabilities": {"firstMatch": [{"appium:platformVersion": "8.1.0", "appium:automationName": "UiAutomator2", "appium:udid": "3300f4b7d5f56461", "appium:appPackage": "com.mavenir.gmid", "platformName": "Android", "appium:fullReset": "false", "appium:appActivity": "com.mavenir.ucc.tab.TabActivity", "appium:deviceName": "Device", "appium:noReset": "true", "appium:newCommandTimeout": "3600"}]}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:4723
DEBUG:urllib3.util.retry:Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000003566160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /wd/hub/session
DEBUG:urllib3.connectionpool:Starting new HTTP connection (2): localhost:4723
DEBUG:urllib3.util.retry:Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000003566240>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /wd/hub/session
DEBUG:urllib3.connectionpool:Starting new HTTP connection (3): localhost:4723
DEBUG:urllib3.util.retry:Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000035663C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /wd/hub/session
DEBUG:urllib3.connectionpool:Starting new HTTP connection (4): localhost:4723
ERROR:root: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000035664E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
ERROR:root: Login and Logout test is failed for user:[user5]
